###
GET http://localhost:3000/api/tareas

### Listar solo tareas COMPLETADAS
GET http://localhost:3000/api/tareas?completada=true

### Listar solo tareas PENDIENTES
GET http://localhost:3000/api/tareas?completada=false

### Crear nueva tarea
POST http://localhost:3000/api/tareas
Content-Type: application/json

{
  "nombre": "Comprar verduras en el supermercado",
  "completada": false
}

### Intentar crear tarea duplicada 
POST http://localhost:3000/api/tareas
Content-Type: application/json

{
  "nombre": "Ir al gimnasio"
}

### Actualizar tarea,Marcar como completada
PUT http://localhost:3000/api/tareas/2
Content-Type: application/json

{
  "nombre": "Sacar a pasear al perro",
  "completada": true
}

### Eliminar tarea
DELETE http://localhost:3000/api/tareas/1